name: hello-pipeline

on:
  push:
    branches: [main]

jobs:
  greet-user:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code in repo
        uses: actions/checkout@v4

      - name: Print greetings
        run: echo " Print Hello from GitHub Actions!"
